### ISSUE TITLE
Multiple Dockerfiles

### ISSUE THREAD

**Issue by Omrigan** [yandexdataschool/Practical_RL#42]
There is a Dockerfile in the root of the repo

Also there is a separate Dockerfile in a folder docker/

Which one is right? Is it possible to run the repo in mybinder and everware with a correct Dockerfile?

**Comment by justheuristic** [comment]
practical_rl/Dockerfile is for binder
practical_rl/docker/Dockerfile is for local containers.

Would be nice to converge to a single dockerfile but turns out binder adds some commands on top of your dockerfile for it to work AND depends on andrewosh/binder-base  AND has an issue with maximum number of linked c++
