### ISSUE TITLE
issues with gym

### ISSUE THREAD

**Issue by justheuristic** [yandexdataschool/Practical_RL#5]
If there's something wrong with openai gym and chat didn't resolve it in 10 minutes, feel free to complain here.

**Comment by justheuristic** [comment]
Contributed by Sergey Kolesnikov:

### no GLX on GPU nodes
```GLXInfoException: pyglet requires an X server with GLX```
Solution: re-install GPU drivers __without opengl__.
https://github.com/openai/gym/issues/366
https://davidsanwald.github.io/2016/11/13/building-tensorflow-with-gpu-support.html

**Comment by justheuristic** [comment]
### Game ends in 200 ticks
The current newest version of gym force-stops environment in 200 steps even if you don't use env.monitor.
This may ruin CEM on MountainCar and others.(week1 homework)
To avoid this, use ```env = gym.make("MountainCar-v0").env```

**Comment by oscartsai** [comment]
For the bonus part of week 0 homework, what is the expected time to solve "taxi-v1" with a genetic algorithm? The problem is that game ends in 200 ticks and in the end all policies in the pool are stuck at -200. If I don't monitor the "is_done" flag and replace it by monitoring when the reward is 20, I find that it would probably take several days to get a score of -100 on my notebook (cpu=i5). So I interrupted the process. I just want to check is it normal?

**Comment by justheuristic** [comment]
For the record, we fixed it by removing time limit (env = gym.make('Taxi-v1').env)
