### ISSUE TITLE
Bugs in Coursera Grading

### ISSUE THREAD

**Issue by marlonjan** [yandexdataschool/Practical_RL#68]
There are various bugs / problems in the grading mechanics. Individual descriptions of the problems can be found in the course forums.

I believe it would be very beneficial to give a quick response in the forums, acknowledging the bugs, and giving people a rough idea when they can expect a fix. Otherwise students will constantly be wondering if it's a problem in the grading or a problem in their solution.

Thanks a lot  : )

**Comment by Abhi001vj** [comment]
I was beta testing the course and I reported some problems but no body responded and I saw no one in forums too.I waited for this course and I wanted to do it with a lot more people so that we could discuss and learn so I tried switching to May 11 session but nothing happens when I click the join session button.Are you taking the course now are you in the May 11 session.I am alone in that course .... :(

**Comment by marlonjan** [comment]
@Abhi001vj To be honest I am not sure in which session I am... However, in my session there are a lot of posts in the forums for week 1 and a few posts for later stages of the course.

**Comment by justheuristic** [comment]
(will fix, eta 24h)

**Comment by marlonjan** [comment]
@Abhi001vj Yes, I completed it a few months ago. Back then there were still a few issues but it was possible to solve them by editing the submission scripts. Great course overall, and even better if the bugs have been fixed by now!

Feel free to close this issue if everything works.

**Comment by justheuristic** [comment]
(we just started fixing 'em. i'll close this issue since we've opened separate issues for major bugs. Thanks guys for pushing us into fixing it :) )
